In [1]:
import requests
from bs4 import BeautifulSoup

In [2]:
url = "https://apps.apple.com/eg/app/zipair/id1512911039"

response = requests.get(url)

response.status_code

200

In [3]:
html = response.text

print(html[:1000])

<!DOCTYPE html>
<html dir="ltr" lang="en-GB">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="applicable-device" content="pc,mobile" />
        <meta name="referrer" content="strict-origin" />

        <link
            rel="apple-touch-icon"
            sizes="180x180"
            href="/assets/favicon/favicon-180.png"
        />

        <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="/assets/favicon/favicon-32.png"
        />

        <link
            rel="icon"
            type="image/png"
            sizes="16x16"
            href="/assets/favicon/favicon-16.png"
        />

        <link
            rel="mask-icon"
            href="/assets/favicon/favicon.svg"
            color="#1d70f2"
        />

        <link rel="manifest" href="/manifest.json" />
        <title>â

In [4]:
"Version History" in html

True

In [5]:
index = html.find("Version History")

print(index)

62537

In [6]:
print(html[index-1000:index+2000])

5 0 81.137c0 3.653 2.96 6.55 6.641 6.55 1.796 0 3.334-.601 4.572-1.877l37.561-36.746c1.636-1.591 2.334-3.25 2.334-5.23Z"></path></svg></span></div></div> </button>  <dialog data-testid="dialog" class="svelte-1p01z7" id="" aria-hidden="true"><div data-testid="content-modal" class="content-modal-container svelte-1ih6d3u" dir="auto"><div class="button-container svelte-1ih6d3u"><button data-testid="content-modal-close-button" class="close-button svelte-1ih6d3u" type="button" aria-label="Close"><svg width="18" height="18" viewBox="0 0 18 18" aria-hidden="true" data-testid="content-modal-close-button-svg"><path d="M1.2 18C.6 18 0 17.5 0 16.8c0-.4.1-.6.4-.8l7-7-7-7c-.3-.2-.4-.5-.4-.8C0 .5.6 0 1.2 0c.3 0 .6.1.8.3l7 7 7-7c.2-.2.5-.3.8-.3.6 0 1.2.5 1.2 1.2 0 .3-.1.6-.4.8l-7 7 7 7c.2.2.4.5.4.8 0 .7-.6 1.2-1.2 1.2-.3 0-.6-.1-.8-.3l-7-7-7 7c-.2.1-.5.3-.8.3z"></path></svg></button> </div> <div class="header-container svelte-1ih6d3u"><h1 data-testid="content-modal-title" class="title svelte-1ih6d3u">Version History</h1> </div> <div class="content-container svelte-1ih6d3u"><ul><li><div class="container detail  svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5">  <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Add information about the Kuala Lumpur route<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.20</span> <time datetime="2026-07-22" class="svelte-1t5dyc5">22 Jul</time></div></div> </div> </li><li><div class="container detail  svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5">  <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.19</span> <time datetime="2026-06-09" class="svelte-1t5dyc5">9 Jun</time></div></div> </div> </li><li><div class="container detail  svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5">  <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.17</span> <time datetime="2026-05-13" class="svelte-1t5dyc5">13 May</time></div></div> </div> </li><li><div class="container detail  svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5">  <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Add eVISA application guide<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.16</span> <time datetime="2026-04-21" class="svelte-1t5dyc5">21 Apr</time></div></div> </div> </li><li><div class="container detail  svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5">  <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.14</span> <time dat

In [7]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(html, "html.parser")

# Version Historyのタイトルを探す
title = soup.find("h1", string="Version History")

title

In [8]:
container = title.find_parent("div", class_="content-container")

container

In [10]:
updates = []

for item in container.find_all("li"):
    
    version = item.find("span").text.strip()
    date = item.find("time")["datetime"]
    note = item.find("p").text.strip()
    
    updates.append({
        "version": version,
        "date": date,
        "release_note": note
    })

updates

AttributeError: 'NoneType' object has no attribute 'find_all'

In [11]:
title = soup.find("h1", string="Version History")

print(title)

<h1 class="title svelte-1ih6d3u" data-testid="content-modal-title">Version History</h1>

In [12]:
container = title.find_next("div", class_="content-container")

print(container)

<div class="content-container svelte-1ih6d3u"><ul><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Add information about the Kuala Lumpur route<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.20</span> <time class="svelte-1t5dyc5" datetime="2026-07-22">22 Jul</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.19</span> <time class="svelte-1t5dyc5" datetime="2026-06-09">9 Jun</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.17</span> <time class="svelte-1t5dyc5" datetime="2026-05-13">13 May</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Add eVISA application guide<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.16</span> <time class="svelte-1t5dyc5" datetime="2026-04-21">21 Apr</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.14</span> <time class="svelte-1t5dyc5" datetime="2026-03-31">31 Mar</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.13</span> <time class="svelte-1t5dyc5" datetime="2026-03-24">24 Mar</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.12</span> <time class="svelte-1t5dyc5" datetime="2026-03-19">19 Mar</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.10</span> <time class="svelte-1t5dyc5" datetime="2026-03-10">10 Mar</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.9</span> <time class="svelte-1t5dyc5" datetime="2026-01-27">27 Jan</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.8</span> <time class="svelte-1t5dyc5" datetime="2026-01-14">14 Jan</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.7</span> <time class="svelte-1t5dyc5" datetime="2025-12-12">12/12/2025</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Add information for the Taipei route.<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.6</span> <time class="svelte-1t5dyc5" datetime="2025-12-10">10/12/2025</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Add information for the Orlando route.<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.5</span> <time class="svelte-1t5dyc5" datetime="2025-12-03">03/12/2025</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.4</span> <time class="svelte-1t5dyc5" datetime="2025-11-12">12/11/2025</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.3</span> <time class="svelte-1t5dyc5" datetime="2025-10-21">21/10/2025</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.2</span> <time class="svelte-1t5dyc5" datetime="2025-10-14">14/10/2025</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Added support for boarding pass display on U.S. routes.
Additional minor updates.<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.1</span> <time class="svelte-1t5dyc5" datetime="2025-08-27">27/08/2025</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Promotion code feature is now available
Other Minor Updates<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.5.0</span> <time class="svelte-1t5dyc5" datetime="2025-07-31">31/07/2025</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.4.6</span> <time class="svelte-1t5dyc5" datetime="2025-07-22">22/07/2025</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.4.5</span> <time class="svelte-1t5dyc5" datetime="2025-03-12">12/03/2025</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.4.4</span> <time class="svelte-1t5dyc5" datetime="2025-03-06">06/03/2025</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.4.3</span> <time class="svelte-1t5dyc5" datetime="2025-01-14">14/01/2025</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.4.2</span> <time class="svelte-1t5dyc5" datetime="2024-10-24">24/10/2024</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Minor function/display corrections<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.4.1</span> <time class="svelte-1t5dyc5" datetime="2024-10-16">16/10/2024</time></div></div> </div> </li><li><div class="container detail svelte-1t5dyc5"><div class="inner svelte-1t5dyc5"><p class="svelte-1t5dyc5"> <span class="svelte-epwvmp"><!-- HTML_TAG_START -->Add information of Houston routes<!-- HTML_TAG_END --> </span></p> <div class="metadata svelte-1t5dyc5"><span class="svelte-1t5dyc5">1.4.0</span> <time class="svelte-1t5dyc5" datetime="2024-10-10">10/10/2024</time></div></div> </div> </li></ul></div>

In [13]:
updates = []

for item in container.find_all("li"):
    
    version = item.find("span").text.strip()
    date = item.find("time")["datetime"]
    note = item.find("p").text.strip()
    
    updates.append({
        "version": version,
        "date": date,
        "release_note": note
    })

updates

[{'version': 'Add information about the Kuala Lumpur route',
  'date': '2026-07-22',
  'release_note': 'Add information about the Kuala Lumpur route'},
 {'version': 'Minor function/display corrections',
  'date': '2026-06-09',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2026-05-13',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Add eVISA application guide',
  'date': '2026-04-21',
  'release_note': 'Add eVISA application guide'},
 {'version': 'Minor function/display corrections',
  'date': '2026-03-31',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2026-03-24',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2026-03-19',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2026-03-10',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2026-01-27',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2026-01-14',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2025-12-12',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Add information for the Taipei route.',
  'date': '2025-12-10',
  'release_note': 'Add information for the Taipei route.'},
 {'version': 'Add information for the Orlando route.',
  'date': '2025-12-03',
  'release_note': 'Add information for the Orlando route.'},
 {'version': 'Minor function/display corrections',
  'date': '2025-11-12',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2025-10-21',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2025-10-14',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Added support for boarding pass display on U.S. routes.\nAdditional minor updates.',
  'date': '2025-08-27',
  'release_note': 'Added support for boarding pass display on U.S. routes.\nAdditional minor updates.'},
 {'version': 'Promotion code feature is now available\nOther Minor Updates',
  'date': '2025-07-31',
  'release_note': 'Promotion code feature is now available\nOther Minor Updates'},
 {'version': 'Minor function/display corrections',
  'date': '2025-07-22',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2025-03-12',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2025-03-06',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2025-01-14',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2024-10-24',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2024-10-16',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Add information of Houston routes',
  'date': '2024-10-10',
  'release_note': 'Add information of Houston routes'}]

In [14]:
print(title)

<h1 class="title svelte-1ih6d3u" data-testid="content-modal-title">Version History</h1>

In [15]:
container = title.find_next("div", class_="content-container")

print(container is None)

False

In [16]:
updates = []

for item in container.find_all("li"):

    version = item.find("span").text.strip()
    date = item.find("time")["datetime"]
    note = item.find("p").get_text(strip=True)

    updates.append({
        "version": version,
        "date": date,
        "release_note": note
    })

updates

[{'version': 'Add information about the Kuala Lumpur route',
  'date': '2026-07-22',
  'release_note': 'Add information about the Kuala Lumpur route'},
 {'version': 'Minor function/display corrections',
  'date': '2026-06-09',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2026-05-13',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Add eVISA application guide',
  'date': '2026-04-21',
  'release_note': 'Add eVISA application guide'},
 {'version': 'Minor function/display corrections',
  'date': '2026-03-31',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2026-03-24',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2026-03-19',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2026-03-10',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2026-01-27',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2026-01-14',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2025-12-12',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Add information for the Taipei route.',
  'date': '2025-12-10',
  'release_note': 'Add information for the Taipei route.'},
 {'version': 'Add information for the Orlando route.',
  'date': '2025-12-03',
  'release_note': 'Add information for the Orlando route.'},
 {'version': 'Minor function/display corrections',
  'date': '2025-11-12',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2025-10-21',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2025-10-14',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Added support for boarding pass display on U.S. routes.\nAdditional minor updates.',
  'date': '2025-08-27',
  'release_note': 'Added support for boarding pass display on U.S. routes.\nAdditional minor updates.'},
 {'version': 'Promotion code feature is now available\nOther Minor Updates',
  'date': '2025-07-31',
  'release_note': 'Promotion code feature is now available\nOther Minor Updates'},
 {'version': 'Minor function/display corrections',
  'date': '2025-07-22',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2025-03-12',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2025-03-06',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2025-01-14',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2024-10-24',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Minor function/display corrections',
  'date': '2024-10-16',
  'release_note': 'Minor function/display corrections'},
 {'version': 'Add information of Houston routes',
  'date': '2024-10-10',
  'release_note': 'Add information of Houston routes'}]

In [17]:
import pandas as pd

df_zipair = pd.DataFrame(updates)

df_zipair

,version,date,release_note
0,Add information about the Kuala Lumpur route,2026-07-22,Add information about the Kuala Lumpur route
1,Minor function/display corrections,2026-06-09,Minor function/display corrections
2,Minor function/display corrections,2026-05-13,Minor function/display corrections
3,Add eVISA application guide,2026-04-21,Add eVISA application guide
4,Minor function/display corrections,2026-03-31,Minor function/display corrections
5,Minor function/display corrections,2026-03-24,Minor function/display corrections
6,Minor function/display corrections,2026-03-19,Minor function/display corrections
7,Minor function/display corrections,2026-03-10,Minor function/display corrections
8,Minor function/display corrections,2026-01-27,Minor function/display corrections
9,Minor function/display corrections,2026-01-14,Minor function/display corrections
10,Minor function/display corrections,2025-12-12,Minor function/display corrections
11,Add information for the Taipei route.,2025-12-10,Add information for the Taipei route.
12,Add information for the Orlando route.,2025-12-03,Add information for the Orlando route.
13,Minor function/display corrections,2025-11-12,Minor function/display corrections
14,Minor function/display corrections,2025-10-21,Minor function/display corrections
15,Minor function/display corrections,2025-10-14,Minor function/display corrections
16,Added support for boarding pass display on U.S...,2025-08-27,Added support for boarding pass display on U.S...
17,Promotion code feature is now available\nOther...,2025-07-31,Promotion code feature is now available\nOther...
18,Minor function/display corrections,2025-07-22,Minor function/display corrections
19,Minor function/display corrections,2025-03-12,Minor function/display corrections
20,Minor function/display corrections,2025-03-06,Minor function/display corrections
21,Minor function/display corrections,2025-01-14,Minor function/display corrections
22,Minor function/display corrections,2024-10-24,Minor function/display corrections
23,Minor function/display corrections,2024-10-16,Minor function/display corrections
24,Add information of Houston routes,2024-10-10,Add information of Houston routes

In [18]:
df_zipair["airline"] = "ZIPAIR"

In [19]:
df_zipair.head()

,version,date,release_note,airline
0,Add information about the Kuala Lumpur route,2026-07-22,Add information about the Kuala Lumpur route,ZIPAIR
1,Minor function/display corrections,2026-06-09,Minor function/display corrections,ZIPAIR
2,Minor function/display corrections,2026-05-13,Minor function/display corrections,ZIPAIR
3,Add eVISA application guide,2026-04-21,Add eVISA application guide,ZIPAIR
4,Minor function/display corrections,2026-03-31,Minor function/display corrections,ZIPAIR

In [20]:
df_zipair = df_zipair[
    [
        "airline",
        "version",
        "date",
        "release_note"
    ]
]

df_zipair.head()

,airline,version,date,release_note
0,ZIPAIR,Add information about the Kuala Lumpur route,2026-07-22,Add information about the Kuala Lumpur route
1,ZIPAIR,Minor function/display corrections,2026-06-09,Minor function/display corrections
2,ZIPAIR,Minor function/display corrections,2026-05-13,Minor function/display corrections
3,ZIPAIR,Add eVISA application guide,2026-04-21,Add eVISA application guide
4,ZIPAIR,Minor function/display corrections,2026-03-31,Minor function/display corrections

In [21]:
df_zipair.to_csv(
    "ZIPAIR_app_updates.csv",
    index=False
)

In [22]:
update_count = (
    df_zipair
    .groupby("airline")
    .size()
    .reset_index(name="update_count")
)

update_count

  airline  update_count
0  ZIPAIR            25

In [23]:
import pandas as pd

df_zipair = pd.DataFrame(updates)

df_zipair.head()

,version,date,release_note
0,Add information about the Kuala Lumpur route,2026-07-22,Add information about the Kuala Lumpur route
1,Minor function/display corrections,2026-06-09,Minor function/display corrections
2,Minor function/display corrections,2026-05-13,Minor function/display corrections
3,Add eVISA application guide,2026-04-21,Add eVISA application guide
4,Minor function/display corrections,2026-03-31,Minor function/display corrections

In [25]:
df_zipair["date"] = pd.to_datetime(df_zipair["date"])

In [26]:
df_zipair.dtypes

version                    str
date            datetime64[us]
release_note               str
dtype: object

In [27]:
df_zipair = df_zipair[
    df_zipair["date"] >= "2023-01-01"
]

In [28]:
df_zipair

,version,date,release_note
0,Add information about the Kuala Lumpur route,2026-07-22,Add information about the Kuala Lumpur route
1,Minor function/display corrections,2026-06-09,Minor function/display corrections
2,Minor function/display corrections,2026-05-13,Minor function/display corrections
3,Add eVISA application guide,2026-04-21,Add eVISA application guide
4,Minor function/display corrections,2026-03-31,Minor function/display corrections
5,Minor function/display corrections,2026-03-24,Minor function/display corrections
6,Minor function/display corrections,2026-03-19,Minor function/display corrections
7,Minor function/display corrections,2026-03-10,Minor function/display corrections
8,Minor function/display corrections,2026-01-27,Minor function/display corrections
9,Minor function/display corrections,2026-01-14,Minor function/display corrections
10,Minor function/display corrections,2025-12-12,Minor function/display corrections
11,Add information for the Taipei route.,2025-12-10,Add information for the Taipei route.
12,Add information for the Orlando route.,2025-12-03,Add information for the Orlando route.
13,Minor function/display corrections,2025-11-12,Minor function/display corrections
14,Minor function/display corrections,2025-10-21,Minor function/display corrections
15,Minor function/display corrections,2025-10-14,Minor function/display corrections
16,Added support for boarding pass display on U.S...,2025-08-27,Added support for boarding pass display on U.S...
17,Promotion code feature is now available\nOther...,2025-07-31,Promotion code feature is now available\nOther...
18,Minor function/display corrections,2025-07-22,Minor function/display corrections
19,Minor function/display corrections,2025-03-12,Minor function/display corrections
20,Minor function/display corrections,2025-03-06,Minor function/display corrections
21,Minor function/display corrections,2025-01-14,Minor function/display corrections
22,Minor function/display corrections,2024-10-24,Minor function/display corrections
23,Minor function/display corrections,2024-10-16,Minor function/display corrections
24,Add information of Houston routes,2024-10-10,Add information of Houston routes

In [29]:
df_zipair["airline"] = "ZIPAIR"

In [30]:
df_zipair.head()

,version,date,release_note,airline
0,Add information about the Kuala Lumpur route,2026-07-22,Add information about the Kuala Lumpur route,ZIPAIR
1,Minor function/display corrections,2026-06-09,Minor function/display corrections,ZIPAIR
2,Minor function/display corrections,2026-05-13,Minor function/display corrections,ZIPAIR
3,Add eVISA application guide,2026-04-21,Add eVISA application guide,ZIPAIR
4,Minor function/display corrections,2026-03-31,Minor function/display corrections,ZIPAIR

In [31]:
def classify_update(note):
    
    note = note.lower()
    
    if "route" in note or "destination" in note:
        return "Network Expansion"
    
    elif "boarding" in note or "check" in note or "visa" in note:
        return "Customer Experience"
    
    elif "payment" in note:
        return "Payment"
    
    elif "add" in note or "new" in note:
        return "Feature"
    
    else:
        return "Maintenance"

In [32]:
df_zipair["category"] = df_zipair["release_note"].apply(classify_update)

In [33]:
df_zipair[[
    "date",
    "release_note",
    "category"
]]

,date,release_note,category
0,2026-07-22,Add information about the Kuala Lumpur route,Network Expansion
1,2026-06-09,Minor function/display corrections,Maintenance
2,2026-05-13,Minor function/display corrections,Maintenance
3,2026-04-21,Add eVISA application guide,Customer Experience
4,2026-03-31,Minor function/display corrections,Maintenance
5,2026-03-24,Minor function/display corrections,Maintenance
6,2026-03-19,Minor function/display corrections,Maintenance
7,2026-03-10,Minor function/display corrections,Maintenance
8,2026-01-27,Minor function/display corrections,Maintenance
9,2026-01-14,Minor function/display corrections,Maintenance
10,2025-12-12,Minor function/display corrections,Maintenance
11,2025-12-10,Add information for the Taipei route.,Network Expansion
12,2025-12-03,Add information for the Orlando route.,Network Expansion
13,2025-11-12,Minor function/display corrections,Maintenance
14,2025-10-21,Minor function/display corrections,Maintenance
15,2025-10-14,Minor function/display corrections,Maintenance
16,2025-08-27,Added support for boarding pass display on U.S...,Network Expansion
17,2025-07-31,Promotion code feature is now available\nOther...,Maintenance
18,2025-07-22,Minor function/display corrections,Maintenance
19,2025-03-12,Minor function/display corrections,Maintenance
20,2025-03-06,Minor function/display corrections,Maintenance
21,2025-01-14,Minor function/display corrections,Maintenance
22,2024-10-24,Minor function/display corrections,Maintenance
23,2024-10-16,Minor function/display corrections,Maintenance
24,2024-10-10,Add information of Houston routes,Network Expansion

In [34]:
def classify_update(note):
    
    note = note.lower()
    
    if "boarding" in note or "check" in note or "visa" in note:
        return "Customer Experience"
    
    elif "payment" in note:
        return "Payment"
    
    elif "route" in note or "destination" in note:
        return "Network Expansion"
    
    elif "add" in note or "new" in note or "feature" in note:
        return "Feature"
    
    else:
        return "Maintenance"

In [35]:
df_zipair["category"] = df_zipair["release_note"].apply(classify_update)

In [36]:
df_zipair[
    df_zipair["release_note"].str.contains(
        "boarding",
        case=False
    )
][
    ["release_note","category"]
]

                                         release_note             category
16  Added support for boarding pass display on U.S...  Customer Experience

In [37]:
len(df_zipair)

25

In [38]:
df_zipair["category"].value_counts()

category
Maintenance            18
Network Expansion       4
Customer Experience     2
Feature                 1
Name: count, dtype: int64

In [39]:
zipair_summary = pd.DataFrame({
    "airline":["ZIPAIR"],
    "updates_2023_2026":[len(df_zipair)]
})

zipair_summary

  airline  updates_2023_2026
0  ZIPAIR                 25

In [40]:
len(df_zipair)

25

In [41]:
zipair_category = (
    df_zipair["category"]
    .value_counts()
    .reset_index()
)

zipair_category.columns = [
    "category",
    "count"
]

zipair_category

              category  count
0          Maintenance     18
1    Network Expansion      4
2  Customer Experience      2
3              Feature      1

In [42]:
zipair_category["percentage"] = (
    zipair_category["count"] 
    / zipair_category["count"].sum()
    * 100
)

zipair_category

              category  count  percentage
0          Maintenance     18        72.0
1    Network Expansion      4        16.0
2  Customer Experience      2         8.0
3              Feature      1         4.0

In [43]:
df_zipair.sort_values("date")

,version,date,release_note,airline,category
24,Add information of Houston routes,2024-10-10,Add information of Houston routes,ZIPAIR,Network Expansion
23,Minor function/display corrections,2024-10-16,Minor function/display corrections,ZIPAIR,Maintenance
22,Minor function/display corrections,2024-10-24,Minor function/display corrections,ZIPAIR,Maintenance
21,Minor function/display corrections,2025-01-14,Minor function/display corrections,ZIPAIR,Maintenance
20,Minor function/display corrections,2025-03-06,Minor function/display corrections,ZIPAIR,Maintenance
19,Minor function/display corrections,2025-03-12,Minor function/display corrections,ZIPAIR,Maintenance
18,Minor function/display corrections,2025-07-22,Minor function/display corrections,ZIPAIR,Maintenance
17,Promotion code feature is now available\nOther...,2025-07-31,Promotion code feature is now available\nOther...,ZIPAIR,Feature
16,Added support for boarding pass display on U.S...,2025-08-27,Added support for boarding pass display on U.S...,ZIPAIR,Customer Experience
15,Minor function/display corrections,2025-10-14,Minor function/display corrections,ZIPAIR,Maintenance
14,Minor function/display corrections,2025-10-21,Minor function/display corrections,ZIPAIR,Maintenance
13,Minor function/display corrections,2025-11-12,Minor function/display corrections,ZIPAIR,Maintenance
12,Add information for the Orlando route.,2025-12-03,Add information for the Orlando route.,ZIPAIR,Network Expansion
11,Add information for the Taipei route.,2025-12-10,Add information for the Taipei route.,ZIPAIR,Network Expansion
10,Minor function/display corrections,2025-12-12,Minor function/display corrections,ZIPAIR,Maintenance
9,Minor function/display corrections,2026-01-14,Minor function/display corrections,ZIPAIR,Maintenance
8,Minor function/display corrections,2026-01-27,Minor function/display corrections,ZIPAIR,Maintenance
7,Minor function/display corrections,2026-03-10,Minor function/display corrections,ZIPAIR,Maintenance
6,Minor function/display corrections,2026-03-19,Minor function/display corrections,ZIPAIR,Maintenance
5,Minor function/display corrections,2026-03-24,Minor function/display corrections,ZIPAIR,Maintenance
4,Minor function/display corrections,2026-03-31,Minor function/display corrections,ZIPAIR,Maintenance
3,Add eVISA application guide,2026-04-21,Add eVISA application guide,ZIPAIR,Customer Experience
2,Minor function/display corrections,2026-05-13,Minor function/display corrections,ZIPAIR,Maintenance
1,Minor function/display corrections,2026-06-09,Minor function/display corrections,ZIPAIR,Maintenance
0,Add information about the Kuala Lumpur route,2026-07-22,Add information about the Kuala Lumpur route,ZIPAIR,Network Expansion

In [44]:
df_zipair.columns

Index(['version', 'date', 'release_note', 'airline', 'category'], dtype='str')

In [45]:
df_zipair = df_zipair[
    [
        "airline",
        "version",
        "date",
        "release_note",
        "category"
    ]
]

In [46]:
df_zipair.to_csv(
    "ZIPAIR_app_updates_2023_2026.csv",
    index=False
)

In [47]:
check = pd.read_csv(
    "ZIPAIR_app_updates_2023_2026.csv"
)

check.head()

,airline,version,date,release_note,category
0,ZIPAIR,Add information about the Kuala Lumpur route,2026-07-22,Add information about the Kuala Lumpur route,Network Expansion
1,ZIPAIR,Minor function/display corrections,2026-06-09,Minor function/display corrections,Maintenance
2,ZIPAIR,Minor function/display corrections,2026-05-13,Minor function/display corrections,Maintenance
3,ZIPAIR,Add eVISA application guide,2026-04-21,Add eVISA application guide,Customer Experience
4,ZIPAIR,Minor function/display corrections,2026-03-31,Minor function/display corrections,Maintenance

In [53]:
airasia_url = "https://apps.apple.com/eg/app/airasia-move-flights-hotels/id565050268"

In [54]:
import requests

html = requests.get(airasia_url).text

print(len(html))

602405

In [55]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(html, "html.parser")

In [56]:
title = soup.find("h1", string="Version History")

print(title)

<h1 class="title svelte-1ih6d3u" data-testid="content-modal-title">Version History</h1>

In [57]:
container = title.find_parent("dialog")

In [58]:
print(container is not None)

True

In [59]:
updates = []

for item in container.find_all("li"):

    metadata = item.find("div", class_="metadata")

    version = metadata.find("span").get_text(strip=True)
    date = metadata.find("time")["datetime"]
    note = item.find("p").get_text(strip=True)

    updates.append({
        "version": version,
        "date": date,
        "release_note": note
    })

In [60]:
updates[:5]

[{'version': '12.50.2',
  'date': '2026-08-03',
  'release_note': 'Your AirAsiaMOVE app just levelled up! \n   Sleeker UI for effortless browsing. \n    Faster performance, every tap. \nUpdate now and travel smarter!'},
 {'version': '12.50.1',
  'date': '2026-07-30',
  'release_note': 'Your AirAsiaMOVE app just levelled up! \n  Sleeker UI for effortless browsing. \n  Faster performance, every tap. \nUpdate now and travel smarter!'},
 {'version': '12.50.0',
  'date': '2026-07-23',
  'release_note': 'Your AirAsiaMOVE app just levelled up! \n  Sleeker UI for effortless browsing. \n  Faster performance, every tap. \nUpdate now and travel smarter!'},
 {'version': '12.49.2',
  'date': '2026-07-15',
  'release_note': 'Your AirAsiaMOVE experience just got better!\n\nUI improvements for smoother navigation. \nOptimized app performance.'},
 {'version': '12.49.1',
  'date': '2026-07-09',
  'release_note': 'Your AirAsiaMOVE experience just got better!\n\nUI improvements for smoother navigation. \nOptimized app performance.'}]

In [61]:
import pandas as pd

df_airasia = pd.DataFrame(updates)

df_airasia.head()

   version        date                                       release_note
0  12.50.2  2026-08-03  Your AirAsiaMOVE app just levelled up! \n   Sl...
1  12.50.1  2026-07-30  Your AirAsiaMOVE app just levelled up! \n  Sle...
2  12.50.0  2026-07-23  Your AirAsiaMOVE app just levelled up! \n  Sle...
3  12.49.2  2026-07-15  Your AirAsiaMOVE experience just got better!\n...
4  12.49.1  2026-07-09  Your AirAsiaMOVE experience just got better!\n...

In [62]:
df_airasia["date"] = pd.to_datetime(df_airasia["date"])

In [63]:
df_airasia = df_airasia[
    df_airasia["date"] >= "2023-01-01"
]

In [64]:
df_airasia.head()

   version       date                                       release_note
0  12.50.2 2026-08-03  Your AirAsiaMOVE app just levelled up! \n   Sl...
1  12.50.1 2026-07-30  Your AirAsiaMOVE app just levelled up! \n  Sle...
2  12.50.0 2026-07-23  Your AirAsiaMOVE app just levelled up! \n  Sle...
3  12.49.2 2026-07-15  Your AirAsiaMOVE experience just got better!\n...
4  12.49.1 2026-07-09  Your AirAsiaMOVE experience just got better!\n...

In [65]:
df_airasia["airline"] = "AirAsia"

In [66]:
df_airasia.head()

,version,date,release_note,airline
0,12.50.2,2026-08-03,Your AirAsiaMOVE app just levelled up! \n Sl...,AirAsia
1,12.50.1,2026-07-30,Your AirAsiaMOVE app just levelled up! \n Sle...,AirAsia
2,12.50.0,2026-07-23,Your AirAsiaMOVE app just levelled up! \n Sle...,AirAsia
3,12.49.2,2026-07-15,Your AirAsiaMOVE experience just got better!\n...,AirAsia
4,12.49.1,2026-07-09,Your AirAsiaMOVE experience just got better!\n...,AirAsia

In [67]:
df_airasia["category"] = df_airasia["release_note"].apply(classify_update)

In [68]:
df_airasia[
    [
        "date",
        "release_note",
        "category"
    ]
].head(10)

        date                                       release_note     category
0 2026-08-03  Your AirAsiaMOVE app just levelled up! \n   Sl...  Maintenance
1 2026-07-30  Your AirAsiaMOVE app just levelled up! \n  Sle...  Maintenance
2 2026-07-23  Your AirAsiaMOVE app just levelled up! \n  Sle...  Maintenance
3 2026-07-15  Your AirAsiaMOVE experience just got better!\n...  Maintenance
4 2026-07-09  Your AirAsiaMOVE experience just got better!\n...  Maintenance
5 2026-06-25  Your AirAsiaMOVE experience just got better!\n...  Maintenance
6 2026-06-14  Your AirAsiaMOVE app just levelled up! \nSleek...  Maintenance
7 2026-06-09  Your AirAsiaMOVE app just levelled up!\n\nSlee...  Maintenance
8 2026-05-22  Your AirAsiaMOVE app just levelled up! \n\nSle...  Maintenance
9 2026-05-21  Your AirAsiaMOVE app just levelled up! \n\nSle...  Maintenance

In [69]:
len(df_airasia)

25

In [70]:
df_airasia["release_note"].head(20)

0     Your AirAsiaMOVE app just levelled up! \n   Sl...
1     Your AirAsiaMOVE app just levelled up! \n  Sle...
2     Your AirAsiaMOVE app just levelled up! \n  Sle...
3     Your AirAsiaMOVE experience just got better!\n...
4     Your AirAsiaMOVE experience just got better!\n...
5     Your AirAsiaMOVE experience just got better!\n...
6     Your AirAsiaMOVE app just levelled up! \nSleek...
7     Your AirAsiaMOVE app just levelled up!\n\nSlee...
8     Your AirAsiaMOVE app just levelled up! \n\nSle...
9     Your AirAsiaMOVE app just levelled up! \n\nSle...
10    Your AirAsiaMOVE experience just got better!\n...
11    Your AirAsiaMOVE experience just got better!\n...
12    Your AirAsiaMOVE experience just got better!\n...
13    Your AirAsiaMOVE app just levelled up! \nSleek...
14    Your AirAsiaMOVE app just levelled up! \nSleek...
15    Your AirAsiaMOVE app just levelled up! \nSleek...
16    Your AirAsiaMOVE experience just got better!\n...
17    Your AirAsiaMOVE experience just got better!\n...
18    Your AirAsiaMOVE experience just got better!\n...
19    Your AirAsiaMOVE experience just got better!\n...
Name: release_note, dtype: str

In [71]:
len(df_airasia)

25

In [72]:
df_airasia.tail()

,version,date,release_note,airline,category
20,12.42.0,2026-02-04,Your AirAsiaMOVE experience just got better! \...,AirAsia,Maintenance
21,12.41.0,2026-01-19,Your AirAsiaMOVE experience just got better!\n...,AirAsia,Maintenance
22,12.40.2,2026-01-06,Your AirAsiaMOVE experience just got better! \...,AirAsia,Maintenance
23,12.40.1,2025-12-13,Your AirAsiaMOVE experience just got better! \...,AirAsia,Maintenance
24,12.40.0,2025-12-05,Your AirAsiaMOVE experience just got better! \...,AirAsia,Maintenance

In [73]:
len(df_airasia)

25

In [74]:
df_airasia.to_csv(
    "AirAsia_app_updates_2023_2026.csv",
    index=False
)

In [75]:
check = pd.read_csv(
    "AirAsia_app_updates_2023_2026.csv"
)

check.head()

,version,date,release_note,airline,category
0,12.50.2,2026-08-03,Your AirAsiaMOVE app just levelled up! \n Sl...,AirAsia,Maintenance
1,12.50.1,2026-07-30,Your AirAsiaMOVE app just levelled up! \n Sle...,AirAsia,Maintenance
2,12.50.0,2026-07-23,Your AirAsiaMOVE app just levelled up! \n Sle...,AirAsia,Maintenance
3,12.49.2,2026-07-15,Your AirAsiaMOVE experience just got better!\n...,AirAsia,Maintenance
4,12.49.1,2026-07-09,Your AirAsiaMOVE experience just got better!\n...,AirAsia,Maintenance

In [76]:
scoot_url = "https://apps.apple.com/us/app/scoot-mobile/id898287610"

In [77]:
html = requests.get(scoot_url).text

print(len(html))

617024

In [78]:
scoot_url = "https://apps.apple.com/us/app/scoot-mobile/id898287610"

html = requests.get(scoot_url).text

print(len(html))

617024

In [79]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(html, "html.parser")

In [80]:
title = soup.find("h1", string="Version History")

print(title)

<h1 class="title svelte-1ih6d3u" data-testid="content-modal-title">Version History</h1>

In [81]:
container = title.find_parent("dialog")

In [82]:
print(container is not None)

True

In [83]:
updates = []

for item in container.find_all("li"):

    metadata = item.find("div", class_="metadata")

    version = metadata.find("span").get_text(strip=True)
    date = metadata.find("time")["datetime"]
    note = item.find("p").get_text(strip=True)

    updates.append({
        "version": version,
        "date": date,
        "release_note": note
    })

In [84]:
updates[:5]

[{'version': '3.31.1',
  'date': '2026-06-19',
  'release_note': "Get ready to fly with more fun! We've made booking and searching a breeze. Discover nearby airports, enjoy personalized currency conversion, and breeze through passenger name entry with our new guidance and single name checkbox. Plus, we've squashed bugs for a smoother, speedier Scoot experience!"},
 {'version': '3.31.0',
  'date': '2026-06-04',
  'release_note': "Get ready to fly with more fun! We've made booking and searching a breeze. Discover nearby airports, enjoy personalized currency conversion, and breeze through passenger name entry with our new guidance and single name checkbox. Plus, we've squashed bugs for a smoother, speedier Scoot experience!"},
 {'version': '3.30.2',
  'date': '2026-05-18',
  'release_note': "Impromptu travels just got easier! \n\nWeâ\x80\x99ve just made a fantastic update to give you more flexibility on the go. You can now book your Scoot flights up to 3 hours before your scheduled departure timeâ\x80\x94down from our previous 4-hour cutoff!\n\nWhether you're locking in a last-minute business trip or fueling a sudden weekend getaway, securing your seat is now faster and more convenient.\n\nPack your bags and get ready for takeoff!"},
 {'version': '3.30.1',
  'date': '2026-05-05',
  'release_note': "Impromptu travels just got easier! \n\nWeâ\x80\x99ve just made a fantastic update to give you more flexibility on the go. You can now book your Scoot flights up to 3 hours before your scheduled departure timeâ\x80\x94down from our previous 4-hour cutoff!\n\nWhether you're locking in a last-minute business trip or fueling a sudden weekend getaway, securing your seat is now faster and more convenient.\n\nPack your bags and get ready for takeoff!"},
 {'version': '3.30.0',
  'date': '2026-04-27',
  'release_note': 'Performance Improvements\nVarious bug fixes and behind-the-scenes enhancements to make your app experience faster and more reliable.'}]

In [85]:
import pandas as pd

df_scoot = pd.DataFrame(updates)

df_scoot.head()

  version        date                                       release_note
0  3.31.1  2026-06-19  Get ready to fly with more fun! We've made boo...
1  3.31.0  2026-06-04  Get ready to fly with more fun! We've made boo...
2  3.30.2  2026-05-18  Impromptu travels just got easier! \n\nWeâve...
3  3.30.1  2026-05-05  Impromptu travels just got easier! \n\nWeâve...
4  3.30.0  2026-04-27  Performance Improvements\nVarious bug fixes an...

In [86]:
df_scoot["date"] = pd.to_datetime(df_scoot["date"])

In [87]:
df_scoot = df_scoot[
    df_scoot["date"] >= "2023-01-01"
]

In [88]:
df_scoot.tail()

   version       date                                       release_note
20  3.17.0 2025-08-27  "Weâve spruced up the app with some nifty ex...
21  3.16.1 2025-08-18  We've made several behind-the-scenes fixes to ...
22  3.16.0 2025-08-05  Weâve fine-tuned the calendar on our flight ...
23  3.15.0 2025-07-03  Plan further ahead - you can now view flight a...
24  3.14.0 2025-06-09  â¢ Flying to or from China or India? Weâve ...

In [89]:
df_scoot["airline"] = "Scoot"

In [90]:
df_scoot.head()

,version,date,release_note,airline
0,3.31.1,2026-06-19,Get ready to fly with more fun! We've made boo...,Scoot
1,3.31.0,2026-06-04,Get ready to fly with more fun! We've made boo...,Scoot
2,3.30.2,2026-05-18,Impromptu travels just got easier! \n\nWeâve...,Scoot
3,3.30.1,2026-05-05,Impromptu travels just got easier! \n\nWeâve...,Scoot
4,3.30.0,2026-04-27,Performance Improvements\nVarious bug fixes an...,Scoot

In [91]:
df_scoot["category"] = df_scoot["release_note"].apply(classify_update)

In [92]:
df_scoot[
    [
        "date",
        "release_note",
        "category"
    ]
].head(10)

,date,release_note,category
0,2026-06-19,Get ready to fly with more fun! We've made boo...,Customer Experience
1,2026-06-04,Get ready to fly with more fun! We've made boo...,Customer Experience
2,2026-05-18,Impromptu travels just got easier! \n\nWeâve...,Maintenance
3,2026-05-05,Impromptu travels just got easier! \n\nWeâve...,Maintenance
4,2026-04-27,Performance Improvements\nVarious bug fixes an...,Maintenance
5,2026-04-13,New Merch Alert!\nYou can now shop for exclusi...,Feature
6,2026-03-27,KrisFlyer Login Updates:\nâ¢ We've revamped t...,Customer Experience
7,2026-03-20,Something Fresh is Landing Soon! \nKeep your e...,Customer Experience
8,2026-03-13,Wheels up on improvements\nâ¢ Gave the login ...,Maintenance
9,2026-02-13,Wheels up on improvements\nâ¢ Gave the login ...,Maintenance

In [93]:
df_scoot.to_csv(
    "Scoot_app_updates_2023_2026.csv",
    index=False
)

In [94]:
pd.read_csv(
    "Scoot_app_updates_2023_2026.csv"
).head()

,version,date,release_note,airline,category
0,3.31.1,2026-06-19,Get ready to fly with more fun! We've made boo...,Scoot,Customer Experience
1,3.31.0,2026-06-04,Get ready to fly with more fun! We've made boo...,Scoot,Customer Experience
2,3.30.2,2026-05-18,Impromptu travels just got easier! \n\nWeâve...,Scoot,Maintenance
3,3.30.1,2026-05-05,Impromptu travels just got easier! \n\nWeâve...,Scoot,Maintenance
4,3.30.0,2026-04-27,Performance Improvements\nVarious bug fixes an...,Scoot,Maintenance

In [95]:
jetstar_url = "https://apps.apple.com/..."

In [96]:
html = requests.get(jetstar_url).text

print(len(html))

2512

In [97]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(html, "html.parser")

In [98]:
title = soup.find("h1", string="Version History")

print(title)

None

In [99]:
id="8f3kq1"
"Version History" in html

False

In [100]:
for keyword in ["What's New", "Release Notes", "version", "release"]:
    print(keyword, keyword in html)

What's New False
Release Notes False
version False
release False

In [101]:
len(html)

2512

In [102]:
print(html[:500])

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="applicable-device" content="pc,mobile" />
        <meta name="referrer" content="strict-origin" />

        <link
            rel="apple-touch-icon"
            sizes="180x180"
            href="/assets/favicon/favicon-180.png"
        />

        <link
            rel="

In [103]:
for keyword in ["softwareVersion", "versionHistory", "whatsNew", "releaseNotes"]:
    print(keyword, keyword in html)

softwareVersion False
versionHistory False
whatsNew False
releaseNotes False

In [104]:
jal_url = "https://apps.apple.com/us/app/japan-airlines/id351785536"

html = requests.get(jal_url).text

print(len(html))

613188

In [105]:
"Version History" in html

True

In [106]:
jal_url = "https://apps.apple.com/us/app/japan-airlines/id351785536"

html = requests.get(jal_url).text

print(len(html))

613188

In [107]:
"Version History" in html

True

In [108]:
soup = BeautifulSoup(html, "html.parser")

title = soup.find("h1", string="Version History")

print(title)

<h1 class="title svelte-1ih6d3u" data-testid="content-modal-title">Version History</h1>

In [109]:
container = title.find_parent("dialog")

In [110]:
print(container is not None)

True

In [111]:
updates = []

for item in container.find_all("li"):

    metadata = item.find("div", class_="metadata")

    version = metadata.find("span").get_text(strip=True)
    date = metadata.find("time")["datetime"]
    note = item.find("p").get_text(strip=True)

    updates.append({
        "version": version,
        "date": date,
        "release_note": note
    })

In [112]:
updates[:5]

[{'version': '6.3.0',
  'date': '2026-07-29',
  'release_note': 'Thank you very much for using the JAL app.\n\n- Passkeys are now available as a login option.\nA passkey is an authentication method that is linked to your device or password manager using a combination of fingerprint, facial, or pattern recognitions.\nIt reduces the risk of unauthorized or illegal logins and phishing scams as there is no need to remember or enter passwords.\n\n- Fixed minor issues.'},
 {'version': '6.2.0',
  'date': '2026-06-29',
  'release_note': 'Thank you very much for using the JAL app.\n- Fixed an issue where seats on international flights were displayed as â\x80\x9cUnassignedâ\x80\x9d even though they had already been assigned.\n- Fixed an issue where expired lounge coupons were displayed.\n- Users can now view usage instructions from the lounge coupon tile.\n- Fixed minor issues.'},
 {'version': '6.1.0',
  'date': '2026-05-21',
  'release_note': 'Thank you very much for using the JAL App.\n- A glitch prevented flight reservations from being displayed for customers with 10 or more boarding records within the past two days, but the issue has now been resolved.\n- Fixed minor issues.'},
 {'version': '6.0.3',
  'date': '2026-04-23',
  'release_note': 'Thank you very much for using the JAL App.\n- Fixed an issue where a personal information consent pop-up appeared repeatedly when transitioning to the website.\n- Improved the JAL Card type display on the Membership screen.\n- Fixed minor issues.'},
 {'version': '6.0.2',
  'date': '2026-04-16',
  'release_note': 'Thank you very much for using the JAL app.\n- We have fixed an issue where reservation information was not being updated correctly for some customers.'}]

In [113]:
import pandas as pd

df_jal = pd.DataFrame(updates)

df_jal.head()

  version        date                                       release_note
0   6.3.0  2026-07-29  Thank you very much for using the JAL app.\n\n...
1   6.2.0  2026-06-29  Thank you very much for using the JAL app.\n- ...
2   6.1.0  2026-05-21  Thank you very much for using the JAL App.\n- ...
3   6.0.3  2026-04-23  Thank you very much for using the JAL App.\n- ...
4   6.0.2  2026-04-16  Thank you very much for using the JAL app.\n- ...

In [114]:
df_jal["date"] = pd.to_datetime(df_jal["date"])

In [115]:
df_jal = df_jal[
    df_jal["date"] >= "2023-01-01"
]

In [116]:
df_jal["airline"] = "JAL"

In [117]:
df_jal.head()

,version,date,release_note,airline
0,6.3.0,2026-07-29,Thank you very much for using the JAL app.\n\n...,JAL
1,6.2.0,2026-06-29,Thank you very much for using the JAL app.\n- ...,JAL
2,6.1.0,2026-05-21,Thank you very much for using the JAL App.\n- ...,JAL
3,6.0.3,2026-04-23,Thank you very much for using the JAL App.\n- ...,JAL
4,6.0.2,2026-04-16,Thank you very much for using the JAL app.\n- ...,JAL

In [118]:
df_jal["category"] = df_jal["release_note"].apply(classify_update)

In [119]:
df_jal[
    [
        "date",
        "release_note",
        "category"
    ]
].head(10)

,date,release_note,category
0,2026-07-29,Thank you very much for using the JAL app.\n\n...,Maintenance
1,2026-06-29,Thank you very much for using the JAL app.\n- ...,Maintenance
2,2026-05-21,Thank you very much for using the JAL App.\n- ...,Customer Experience
3,2026-04-23,Thank you very much for using the JAL App.\n- ...,Maintenance
4,2026-04-16,Thank you very much for using the JAL app.\n- ...,Maintenance
5,2026-04-15,Thank you very much for using the JAL app.\n--...,Feature
6,2026-02-02,Thank you very much for using the JAL app.\n- ...,Maintenance
7,2026-01-15,Thank you very much for using the JAL app.\n- ...,Maintenance
8,2025-12-17,Thank you very much for using the JAL app.\n- ...,Maintenance
9,2025-11-26,Thank you very much for using the JAL app.\n- ...,Maintenance

In [120]:
df_jal.to_csv(
    "JAL_app_updates_2023_2026.csv",
    index=False
)

In [121]:
pd.read_csv(
    "JAL_app_updates_2023_2026.csv"
).head()

,version,date,release_note,airline,category
0,6.3.0,2026-07-29,Thank you very much for using the JAL app.\n\n...,JAL,Maintenance
1,6.2.0,2026-06-29,Thank you very much for using the JAL app.\n- ...,JAL,Maintenance
2,6.1.0,2026-05-21,Thank you very much for using the JAL App.\n- ...,JAL,Customer Experience
3,6.0.3,2026-04-23,Thank you very much for using the JAL App.\n- ...,JAL,Maintenance
4,6.0.2,2026-04-16,Thank you very much for using the JAL app.\n- ...,JAL,Maintenance

In [122]:
zipair = pd.read_csv("ZIPAIR_app_updates_2023_2026.csv")
airasia = pd.read_csv("AirAsia_app_updates_2023_2026.csv")
scoot = pd.read_csv("Scoot_app_updates_2023_2026.csv")
jal = pd.read_csv("JAL_app_updates_2023_2026.csv")

In [ ]:
all_apps = pd.concat(
    [
        zipair,
        airasia,
        scoot,
        jal
    ],
    ignore_index=True
)

In [123]:
all_apps.head()

NameError: name 'all_apps' is not defined

In [124]:
zipair = pd.read_csv("ZIPAIR_app_updates_2023_2026.csv")
airasia = pd.read_csv("AirAsia_app_updates_2023_2026.csv")
scoot = pd.read_csv("Scoot_app_updates_2023_2026.csv")
jal = pd.read_csv("JAL_app_updates_2023_2026.csv")

In [125]:
all_apps = pd.concat(
    [
        zipair,
        airasia,
        scoot,
        jal
    ],
    ignore_index=True
)

In [126]:
all_apps.head()

,version,date,release_note,airline,category
0,1.5.20,2026-07-22,Add information about the Kuala Lumpur route,NaN,NaN
1,1.5.19,2026-06-09,Minor function/display corrections,NaN,NaN
2,1.5.17,2026-05-13,Minor function/display corrections,NaN,NaN
3,1.5.16,2026-04-21,Add eVISA application guide,NaN,NaN
4,1.5.14,2026-03-31,Minor function/display corrections,NaN,NaN

In [127]:
print(zipair.shape)
print(airasia.shape)
print(scoot.shape)
print(jal.shape)

(25, 3)
(25, 5)
(25, 5)
(25, 5)

In [128]:
zipair["airline"] = "ZIPAIR"

In [129]:
zipair["category"] = zipair["release_note"].apply(classify_update)

In [130]:
zipair.head()

,version,date,release_note,airline,category
0,1.5.20,2026-07-22,Add information about the Kuala Lumpur route,ZIPAIR,Network Expansion
1,1.5.19,2026-06-09,Minor function/display corrections,ZIPAIR,Maintenance
2,1.5.17,2026-05-13,Minor function/display corrections,ZIPAIR,Maintenance
3,1.5.16,2026-04-21,Add eVISA application guide,ZIPAIR,Customer Experience
4,1.5.14,2026-03-31,Minor function/display corrections,ZIPAIR,Maintenance

In [131]:
all_apps = pd.concat(
    [
        zipair,
        airasia,
        scoot,
        jal
    ],
    ignore_index=True
)

In [132]:
all_apps.shape

(100, 5)

In [133]:
all_apps["airline"].value_counts()

airline
ZIPAIR     25
AirAsia    25
Scoot      25
JAL        25
Name: count, dtype: int64

In [134]:
all_apps.shape

(100, 5)

In [135]:
update_count = (
    all_apps
    .groupby("airline")
    .size()
    .reset_index(name="update_count")
)

update_count

   airline  update_count
0  AirAsia            25
1      JAL            25
2    Scoot            25
3   ZIPAIR            25

In [136]:
all_apps["date"] = pd.to_datetime(all_apps["date"])

In [137]:
all_apps["year"] = all_apps["date"].dt.year

In [138]:
yearly_updates = (
    all_apps
    .groupby(["airline","year"])
    .size()
    .reset_index(name="updates")
)

yearly_updates

   airline  year  updates
0  AirAsia  2025        2
1  AirAsia  2026       23
2      JAL  2025       17
3      JAL  2026        8
4    Scoot  2025       13
5    Scoot  2026       12
6   ZIPAIR  2024        3
7   ZIPAIR  2025       12
8   ZIPAIR  2026       10

In [139]:
category_mix = (
    all_apps
    .groupby(["airline","category"])
    .size()
    .reset_index(name="count")
)

category_mix

    airline             category  count
0   AirAsia          Maintenance     25
1       JAL  Customer Experience      2
2       JAL              Feature      1
3       JAL          Maintenance     22
4     Scoot  Customer Experience      7
5     Scoot              Feature      7
6     Scoot          Maintenance     11
7    ZIPAIR  Customer Experience      2
8    ZIPAIR              Feature      1
9    ZIPAIR          Maintenance     18
10   ZIPAIR    Network Expansion      4

In [140]:
category_ratio = (
    category_mix
    .assign(
        ratio=lambda x: x["count"] / x.groupby("airline")["count"].transform("sum") * 100
    )
)

category_ratio

    airline             category  count  ratio
0   AirAsia          Maintenance     25  100.0
1       JAL  Customer Experience      2    8.0
2       JAL              Feature      1    4.0
3       JAL          Maintenance     22   88.0
4     Scoot  Customer Experience      7   28.0
5     Scoot              Feature      7   28.0
6     Scoot          Maintenance     11   44.0
7    ZIPAIR  Customer Experience      2    8.0
8    ZIPAIR              Feature      1    4.0
9    ZIPAIR          Maintenance     18   72.0
10   ZIPAIR    Network Expansion      4   16.0

In [141]:
airasia_notes = all_apps[
    all_apps["airline"]=="AirAsia"
][
    ["date","release_note"]
]

airasia_notes.head(10)

         date                                       release_note
25 2026-08-03  Your AirAsiaMOVE app just levelled up! \n   Sl...
26 2026-07-30  Your AirAsiaMOVE app just levelled up! \n  Sle...
27 2026-07-23  Your AirAsiaMOVE app just levelled up! \n  Sle...
28 2026-07-15  Your AirAsiaMOVE experience just got better!\n...
29 2026-07-09  Your AirAsiaMOVE experience just got better!\n...
30 2026-06-25  Your AirAsiaMOVE experience just got better!\n...
31 2026-06-14  Your AirAsiaMOVE app just levelled up! \nSleek...
32 2026-06-09  Your AirAsiaMOVE app just levelled up!\n\nSlee...
33 2026-05-22  Your AirAsiaMOVE app just levelled up! \n\nSle...
34 2026-05-21  Your AirAsiaMOVE app just levelled up! \n\nSle...

In [142]:
def classify_airasia(note):
    note = note.lower()

    if "levelled up" in note or "experience" in note or "sleek" in note:
        return "Customer Experience"
    
    return "Maintenance"

In [143]:
all_apps.loc[
    all_apps["airline"]=="AirAsia",
    "category"
] = all_apps.loc[
    all_apps["airline"]=="AirAsia",
    "release_note"
].apply(classify_airasia)

In [144]:
all_apps[
    all_apps["airline"]=="AirAsia"
]["category"].value_counts()

category
Customer Experience    25
Name: count, dtype: int64

In [145]:
category_mix = (
    all_apps
    .groupby(["airline","category"])
    .size()
    .reset_index(name="count")
)

category_ratio = (
    category_mix
    .assign(
        ratio=lambda x: 
        x["count"] / x.groupby("airline")["count"].transform("sum") * 100
    )
)

category_ratio

    airline             category  count  ratio
0   AirAsia  Customer Experience     25  100.0
1       JAL  Customer Experience      2    8.0
2       JAL              Feature      1    4.0
3       JAL          Maintenance     22   88.0
4     Scoot  Customer Experience      7   28.0
5     Scoot              Feature      7   28.0
6     Scoot          Maintenance     11   44.0
7    ZIPAIR  Customer Experience      2    8.0
8    ZIPAIR              Feature      1    4.0
9    ZIPAIR          Maintenance     18   72.0
10   ZIPAIR    Network Expansion      4   16.0

In [147]:
pivot = category_ratio.pivot(
    index="airline",
    columns="category",
    values="ratio"
).fillna(0)

pivot

category  Customer Experience  Feature  Maintenance  Network Expansion
airline
AirAsia                 100.0      0.0          0.0                0.0
JAL                       8.0      4.0         88.0                0.0
Scoot                    28.0     28.0         44.0                0.0
ZIPAIR                    8.0      4.0         72.0               16.0

In [148]:
pivot.to_csv(
    "airline_app_agility_category_pivot.csv"
)

In [149]:
pd.read_csv(
    "airline_app_agility_category_pivot.csv"
)

   airline  Customer Experience  Feature  Maintenance  Network Expansion
0  AirAsia                100.0      0.0          0.0                0.0
1      JAL                  8.0      4.0         88.0                0.0
2    Scoot                 28.0     28.0         44.0                0.0
3   ZIPAIR                  8.0      4.0         72.0               16.0

In [150]:
waffle_data = []

for _, row in category_ratio.iterrows():
    for i in range(round(row["ratio"])):
        waffle_data.append({
            "airline": row["airline"],
            "category": row["category"],
            "value": 1
        })

waffle_df = pd.DataFrame(waffle_data)

waffle_df.head()

   airline             category  value
0  AirAsia  Customer Experience      1
1  AirAsia  Customer Experience      1
2  AirAsia  Customer Experience      1
3  AirAsia  Customer Experience      1
4  AirAsia  Customer Experience      1

In [151]:
waffle_df.groupby("airline").size()

airline
AirAsia    100
JAL        100
Scoot      100
ZIPAIR     100
dtype: int64

In [152]:
waffle_df.to_csv(
    "airline_digital_agility_waffle.csv",
    index=False
)

In [153]:
pd.read_csv(
    "airline_digital_agility_waffle.csv"
).head()

   airline             category  value
0  AirAsia  Customer Experience      1
1  AirAsia  Customer Experience      1
2  AirAsia  Customer Experience      1
3  AirAsia  Customer Experience      1
4  AirAsia  Customer Experience      1

In [154]:
waffle_df.head()

   airline             category  value
0  AirAsia  Customer Experience      1
1  AirAsia  Customer Experience      1
2  AirAsia  Customer Experience      1
3  AirAsia  Customer Experience      1
4  AirAsia  Customer Experience      1

In [155]:
waffle_df.to_csv(
    "airline_digital_agility_waffle_flourish.csv",
    index=False
)

In [156]:
bubble_df = category_ratio.copy()

bubble_df.head()

   airline             category  count  ratio
0  AirAsia  Customer Experience     25  100.0
1      JAL  Customer Experience      2    8.0
2      JAL              Feature      1    4.0
3      JAL          Maintenance     22   88.0
4    Scoot  Customer Experience      7   28.0

In [157]:
bubble_df["size"] = bubble_df["count"]
bubble_df["label"] = bubble_df["category"]

In [ ]:
bubble_df

In [158]:
bubble_df.to_csv(
    "airline_digital_agility_bubble.csv",
    index=False
)

In [159]:
packed_df = category_ratio.copy()

packed_df["label"] = (
    packed_df["airline"] + " - " + packed_df["category"]
)

packed_df["value"] = packed_df["count"]

packed_df.head()

,airline,category,count,ratio,label,value
0,AirAsia,Customer Experience,25,100.0,AirAsia - Customer Experience,25
1,JAL,Customer Experience,2,8.0,JAL - Customer Experience,2
2,JAL,Feature,1,4.0,JAL - Feature,1
3,JAL,Maintenance,22,88.0,JAL - Maintenance,22
4,Scoot,Customer Experience,7,28.0,Scoot - Customer Experience,7

In [160]:
packed_df.to_csv(
    "airline_packed_circles.csv",
    index=False
)

In [161]:
packed_df["category"] = packed_df["category"].str.strip()

In [162]:
updates_summary = (
    category_ratio
    .groupby("airline")["count"]
    .sum()
    .reset_index()
)

updates_summary

   airline  count
0  AirAsia     25
1      JAL     25
2    Scoot     25
3   ZIPAIR     25

In [163]:
category_summary = (
    category_ratio
    .groupby("airline")["category"]
    .nunique()
    .reset_index()
    .rename(columns={"category":"category_count"})
)

category_summary

   airline  category_count
0  AirAsia               1
1      JAL               3
2    Scoot               3
3   ZIPAIR               4

In [164]:
chart3_df = updates_summary.merge(
    category_summary,
    on="airline"
)

chart3_df

   airline  count  category_count
0  AirAsia     25               1
1      JAL     25               3
2    Scoot     25               3
3   ZIPAIR     25               4

In [165]:
chart3_df["business_model"] = chart3_df["airline"].apply(
    lambda x: "Full-Service Carrier" if x=="JAL" else "LCC"
)

chart3_df

   airline  count  category_count        business_model
0  AirAsia     25               1                   LCC
1      JAL     25               3  Full-Service Carrier
2    Scoot     25               3                   LCC
3   ZIPAIR     25               4                   LCC

In [166]:
chart3_df = chart3_df.rename(
    columns={"count":"updates"}
)

chart3_df

   airline  updates  category_count        business_model
0  AirAsia       25               1                   LCC
1      JAL       25               3  Full-Service Carrier
2    Scoot       25               3                   LCC
3   ZIPAIR       25               4                   LCC

In [167]:
chart3_df.to_csv(
    "digital_agility_matrix.csv",
    index=False
)